#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

MUNIN_PLUGINS="
	postfix_mailvolume
	postfix_mailstats
	postfix_mailqueue
	postgrey
	clamav
	spamassassin
	ps_smtpd
	fail2ban
	dovecot
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Import fail2ban smf"
svccfg import /opt/local/lib/svc/manifest/fail2ban.xml

echo "* Setup vmail"
groupadd -g 155 vmail
useradd -m -s /usr/bin/false -d /var/mail -u 155 -g vmail vmail
# passwd -N vmail
# passwd -d vmail

echo "* Make mail folder unwritable without nfs"
mkdir -p /var/mail
chown root:root /var/mail
chmod 0750 /var/mail

echo "* Backup original config files"
cp /opt/local/etc/postfix/main.cf /opt/local/etc/postfix/main.cf.bak
cp /opt/local/etc/postfix/master.cf /opt/local/etc/postfix/master.cf.bak
cp /opt/local/etc/amavisd.conf /opt/local/etc/amavisd.conf.bak
cp /opt/local/etc/clamd.conf /opt/local/etc/clamd.conf.bak
cp /opt/local/etc/freshclam.conf /opt/local/etc/freshclam.conf.bak
cp /opt/local/etc/policyd-weight.conf /opt/local/etc/policyd-weight.conf.bak
cp /opt/local/etc/policyd.conf /opt/local/etc/policyd.conf.bak
cp /opt/local/etc/dovecot/dovecot.conf /opt/local/etc/dovecot/dovecot.conf.bak

echo "* Set Folder rights"
chmod 0750 /opt/local/etc/postfix/sql
chmod 0640 /opt/local/etc/postfix/sql/*
chown -R root:postfix /opt/local/etc/postfix/sql
chmod 0600 /opt/local/etc/dovecot/dovecot-sql.conf
chown root:root /opt/local/etc/dovecot/dovecot-sql.conf

echo "* Setup clamav-unofficial-sigs"
mkdir -p /var/log/clamav-unofficial-sigs

# Clean up
echo "* Cleaning up."
rm /root/customize
/usr/sbin/svccfg delete svc:/pkgsrc/nullmailer

# Prepare image for provisioning
sm-prepare-image -y
